# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad9d679e7774f15a292836945fbbdb08e0eba8fadfcb08f5eb25c7ca7c9637b07bec208f2ed0a6c6aaeb020df96279cb7d64d65b3fedd24a83dc71a9dc9ee11d

test:
  secret_key_base: 431ef951ae2e82efdda8318359e660eb111908914c3d00bd61e8ad1fd14af87f467dc0515df906d3e691d938bb9a75949ae7fd8ea4a911239571c4be37fa6989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
